GlobalTemplateDownloadLocation: https://github.com/Modelhelper/templates/releases/latest/download/mh-templates.zip
TemplateLocations: 
  Global: C:\dev\projects\hpe\mh-templates\src
  Shared: C:\dev\projects\hpe\mh-templates\src
Options:
  Folder: Histology
Projects:
  cs.core:
    Language: cs
    Code: 
      Locations:
  cs.net:
    Language: cs
  angular:
    Language: ts
    Code: 
      Locations: